create table "public"."featured" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "product" bigint
);


alter table "public"."featured" enable row level security;

CREATE UNIQUE INDEX featured_pkey ON public.featured USING btree (id);

alter table "public"."featured" add constraint "featured_pkey" PRIMARY KEY using index "featured_pkey";

alter table "public"."featured" add constraint "featured_product_fkey" FOREIGN KEY (product) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."featured" validate constraint "featured_product_fkey";

grant delete on table "public"."featured" to "anon";

grant insert on table "public"."featured" to "anon";

grant references on table "public"."featured" to "anon";

grant select on table "public"."featured" to "anon";

grant trigger on table "public"."featured" to "anon";

grant truncate on table "public"."featured" to "anon";

grant update on table "public"."featured" to "anon";

grant delete on table "public"."featured" to "authenticated";

grant insert on table "public"."featured" to "authenticated";

grant references on table "public"."featured" to "authenticated";

grant select on table "public"."featured" to "authenticated";

grant trigger on table "public"."featured" to "authenticated";

grant truncate on table "public"."featured" to "authenticated";

grant update on table "public"."featured" to "authenticated";

grant delete on table "public"."featured" to "service_role";

grant insert on table "public"."featured" to "service_role";

grant references on table "public"."featured" to "service_role";

grant select on table "public"."featured" to "service_role";

grant trigger on table "public"."featured" to "service_role";

grant truncate on table "public"."featured" to "service_role";

grant update on table "public"."featured" to "service_role";


