create table "public"."products_category" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label" character varying not null default ''::character varying,
    "isActive" boolean not null default true
);


alter table "public"."products_category" enable row level security;

CREATE UNIQUE INDEX products_category_pkey ON public.products_category USING btree (id);

alter table "public"."products_category" add constraint "products_category_pkey" PRIMARY KEY using index "products_category_pkey";

grant delete on table "public"."products_category" to "anon";

grant insert on table "public"."products_category" to "anon";

grant references on table "public"."products_category" to "anon";

grant select on table "public"."products_category" to "anon";

grant trigger on table "public"."products_category" to "anon";

grant truncate on table "public"."products_category" to "anon";

grant update on table "public"."products_category" to "anon";

grant delete on table "public"."products_category" to "authenticated";

grant insert on table "public"."products_category" to "authenticated";

grant references on table "public"."products_category" to "authenticated";

grant select on table "public"."products_category" to "authenticated";

grant trigger on table "public"."products_category" to "authenticated";

grant truncate on table "public"."products_category" to "authenticated";

grant update on table "public"."products_category" to "authenticated";

grant delete on table "public"."products_category" to "service_role";

grant insert on table "public"."products_category" to "service_role";

grant references on table "public"."products_category" to "service_role";

grant select on table "public"."products_category" to "service_role";

grant trigger on table "public"."products_category" to "service_role";

grant truncate on table "public"."products_category" to "service_role";

grant update on table "public"."products_category" to "service_role";


